---
- hosts: all
  become: true
  tasks:
  - name: Install Apache
    apt:
      name: apache2
  - name: Start apache on boot
    service:
      name: apache
      state: started
      enabled: true
  - name: copy over ssh
    ansible.builtin.copy:
      src: index13.html
      dest: /var/www/html/index13.html
